### ISSUE TITLE
Exception in get_bucket_names

### ISSUE THREAD

**Issue by Arkoprabho** [kiran94/s3edit.nvim#6]
```
   Error  19:39:35 msg_show.lua_error   S3Edit E5108: Error executing lua Vim:E474: Unidentified byte: Buckets:
- CreationDate: '2021-11-20T10:09:47+00:00'
  Name: <bucket_name>
- CreationDate: '2021-11-20T09:52:18+00:00'
  Name: <bucket_name>
......
stack traceback:
	[C]: in function 'json_decode'
	...vim/site/pack/packer/start/s3edit.nvim/lua/s3edit/s3.lua:12: in function 'get_bucket_names'
	...m/site/pack/packer/start/s3edit.nvim/lua/s3edit/init.lua:36: in function 'edit'
	[string ":lua"]:1: in main chunk
```

It does list the bucket names correctly, but throws an exception with the above stack trace

**Comment by kiran94** [comment]
Thanks for reporting this issue @Arkoprabho  

Could you provide some information on your environment to help me debug the issue. The following would be helpful: 

```bash
aws --version
nvim --version
```

Then could you check if the following commands yield properly formed `json` (no need to paste the output, just want to know if they are properly formatted): 

```bash
aws s3api list-buckets
```

You can programmatically check if it's properly formed `json` using something like [`jq`](https://stedolan.github.io/jq/) for example: 

```bash
aws s3api list-buckets | jq .
```

Additionally are there any non-UTF8 or special characters in the bucket names you are getting back? The failure looks to be happening between when we get the bucket listings from AWS and then try to decode it using Neovim's built in `json_decode` method. The documentation mentions: 

> Note: function treats its input as UTF-8 always.  The JSON
		standard allows only a few encodings, of which UTF-8 is
		recommended and the only one required to be supported.
		Non-UTF-8 characters are an error.

So I am wondering if we are running into that here.

**Comment by kiran94** [comment]
Hey @Arkoprabho Let me know if you get a chance to look at the above

**Comment by Arkoprabho** [comment]
Hey there
Apologies for the late reply. Was vacationing.
Here are the details:

```
❯ aws --version                                                     
aws-cli/2.10.3 Python/3.9.11 Darwin/22.4.0 exe/x86_64 prompt/off
```

```
❯ nvim --version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```

Regarding the output of `aws s3api list-buckets`, my output format is YAML. Now I suspect the entire issue is due to this. Perhaps we can add a `--output json` while executing the commands from lua to enfore that we get the correct outputs
